version: "3.1"
services:
    icms:
        build: .
        ports: 
            - ${HTTP_PORT}:80
        volumes:
            - ./icms2:/var/www/html/
            - ./php:/usr/local/etc/php/
        links:
            - mysql
        networks:
            - default
    mysql:
        image: mysql:8.0
        ports: 
            - 3306:3306
        command: --default-authentication-plugin=caching_sha2_password
        environment:
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_INITDB_SKIP_TZINFO: 1
        volumes:
            - ./mysql/dump:/docker-entrypoint-initdb.d
            - ./mysql/conf:/etc/mysql/conf.d
            - ./mysql/db:/var/lib/mysql
        networks:
            - default
