<?php
return array(

	'root'								=> '/',
	'host'								=> 'http://localhost',
	'upload_root'						=> '/upload/',
	'upload_host'						=> 'http://localhost/upload',
	'cache_root'						=> '/cache/',
	'is_site_on'						=> 1,
	'off_reason'						=> 'Идут технические работы',
	'sitename'							=> 'InstantCMS 2',
	'hometitle'							=> 'InstantCMS 2',
	'date_format'						=> 'd.m.Y',
	'date_format_js'					=> 'dd.mm.yy',
	'time_zone'							=> 'Europe/Moscow',
	'allow_users_time_zone'				=> 1,
	'template'							=> 'modern',
	'template_admin'					=> 'admincoreui',
	'template_mobile'					=> '',
	'template_tablet'					=> '',
	'db_host'							=> 'mysql',
	'db_base'							=> 'icmsdb',
	'db_user'							=> 'icmsdb',
	'db_pass'							=> 'secret',
	'db_prefix'							=> 'cms_',
	'db_engine'							=> 'InnoDB',
	'db_charset'						=> 'utf8mb4',
	'clear_sql_mode'					=> 1,
	'innodb_full_text'					=> 1,
	'db_users_table'					=> 'cms_users',
	'language'							=> 'ru',
	'metakeys'							=> 'ключевые, слова, сайта',
	'metadesc'							=> 'Описание сайта',
	'ct_autoload'						=> 'frontpage',
	'ct_default'						=> 'content',
	'frontpage'							=> 'none',
	'debug'								=> 0,
	'emulate_lag'						=> '',
	'cache_enabled'						=> 0,
	'cache_method'						=> 'files',
	'cache_ttl'							=> 300,
	'cache_host'						=> 'localhost',
	'cache_port'						=> 11211,
	'min_html'							=> 0,
	'merge_css'							=> 0,
	'merge_js'							=> 0,
	'mail_transport'					=> 'mail',
	'mail_from'							=> 'noreply@example.com',
	'mail_from_name'					=> '',
	'mail_smtp_server'					=> 'smtp.example.com',
	'mail_smtp_port'					=> 25,
	'mail_smtp_auth'					=> 1,
	'mail_smtp_user'					=> 'user@example.com',
	'mail_smtp_pass'					=> '',
	'is_check_updates'					=> 1,
	'detect_ip_key'						=> 'REMOTE_ADDR',
	'allow_ips'							=> '',
	'default_editor'					=> 3,
	'show_breadcrumbs'					=> 1,
	'check_spoofing_type'				=> 0,
	'production_time'					=> 1727857574,
	'native_yaml'						=> 0,
	'session_save_handler'				=> 'files',
	'session_name'						=> 'ICMS66FD03A59DD81',
	'session_save_path'					=> '/tmp/66fd02a743c63',
	'session_maxlifetime'				=> 24,
	'controllers_without_widgets'		=> array (
  0 => 'admin',
),
	'ctype_default'						=> array (
),

);
